create or replace function stc_text_width(p_text text) returns integer as $$
declare
  i integer;
  l integer = 0;
  c char;
begin
  for i in 1..length(p_text) loop
    c = substr(p_text, i, 1);
    if    c in ('a', 'ą') then l = l + 7;
    elsif c = 'b' then l = l + 8;
    elsif c in ('c', 'č') then l = l + 7;
    elsif c = 'd' then l = l + 8;
    elsif c in ('e', 'ę', 'ė') then l = l + 7;
    elsif c = 'f' then l = l + 6;
    elsif c = 'g' then l = l + 8;
    elsif c = 'h' then l = l + 9;
    elsif c in ('i', 'į') then l = l + 4;
    elsif c = 'j' then l = l + 5;
    elsif c = 'k' then l = l + 8;
    elsif c = 'l' then l = l + 4;
    elsif c = 'm' then l = l + 13;
    elsif c = 'n' then l = l + 9;
    elsif c = 'o' then l = l + 8;
    elsif c = 'p' then l = l + 8;
    elsif c = 'q' then l = l + 8;
    elsif c = 'r' then l = l + 7;
    elsif c in ('s', 'š') then l = l + 6;
    elsif c = 't' then l = l + 6;
    elsif c in ('u', 'ų', 'ū') then l = l + 8;
    elsif c = 'v' then l = l + 8;
    elsif c = 'w' then l = l + 11;
    elsif c = 'x' then l = l + 8;
    elsif c = 'y' then l = l + 8;
    elsif c in ('z', 'ž') then l = l + 7;
    elsif c in ('A', 'Ą') then l = l + 10;
    elsif c = 'B' then l = l + 9;
    elsif c in ('C', 'Č') then l = l + 10;
    elsif c = 'D' then l = l + 10;
    elsif c in ('E', 'Ę', 'Ė') then l = l + 9;
    elsif c = 'F' then l = l + 8;
    elsif c = 'G' then l = l + 10;
    elsif c = 'H' then l = l + 11;
    elsif c in ('I', 'Į') then l = l + 5;
    elsif c = 'Į' then l = l + 5;
    elsif c = 'J' then l = l + 6;
    elsif c = 'K' then l = l + 10;
    elsif c = 'L' then l = l + 8;
    elsif c = 'M' then l = l + 12;
    elsif c = 'N' then l = l + 10;
    elsif c = 'O' then l = l + 10;
    elsif c = 'P' then l = l + 8;
    elsif c = 'Q' then l = l + 11;
    elsif c = 'R' then l = l + 10;
    elsif c in ('S', 'Š') then l = l + 8;
    elsif c = 'T' then l = l + 9;
    elsif c in ('U', 'Ų', 'Ū') then l = l + 10;
    elsif c = 'V' then l = l + 10;
    elsif c = 'X' then l = l + 9;
    elsif c = 'Y' then l = l + 10;
    elsif c in ('Z', 'Ž') then l = l + 8;
    elsif c in ('.', ':') then l = l + 4;
    elsif c = ' ' then l = l + 3;
    elsif c = '(' then l = l + 4;
    elsif c = ')' then l = l + 4;
    elsif c = ',' then l = l + 4;
    elsif c = '-' then l = l + 7;
    else raise 'NEŽINOMAS SIMBOLIO % PLOTIS ŽODYJE %', c, p_text;
    end if;
  end loop;
  return l;
end$$ language plpgsql;
